name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install tree-sitter CLI
      run: npm -g install tree-sitter-cli
    
    - name: Run tests
      run: make test

