name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install npm
      uses: actions/setup-node@v5
      with:
        node-version: 'latest'

    - name: Install deps
      run: npm ci
    
    - name: Run tests
      run: make test

